@url = http://localhost:3000

#############################################################
### try global variables
#############################################################
###
GET {{url}}/ HTTP/1.1
###
